@startuml diagramaDeAtividade

start

:ler configurações;
:setup coração;
:setup veias;
:setup estenose;

repeat :calcular pulso; 
    :computar coração;
    repeat :capturar imagem; 
        :aplicar efeito de fundo;
        :aplicar ruido branco;
    repeat while (novo valor de pulso?) is (sim)
repeat while (novo valor de perspectiva?) is (sim)

:salvar imagens geradas;

stop

@enduml