@startuml diagramaDeAtividade

start

:ler configurações;
:setup coração;
:setup veias;
:setup estenose;

repeat :valor do pulso
    :calcular pulso;
    :computar coração;
    repeat :perspectiva
        :capturar imagem;
        :aplicar efeito de fundo;
        :aplicar ruido branco;
    repeat while
repeat while

:salvar imagens geradas;

stop

@enduml